# Numpy

## 1D Array

In [6]:
import numpy

In [34]:
myArray1=numpy.array([1,2,3,4,5],dtype=str)
print("the Array is ", myArray1, type(myArray1))

the Array is  ['1' '2' '3' '4' '5'] <class 'numpy.ndarray'>


### Copy Array

In [32]:
myArray2=myArray1.copy()

### View Array

In [33]:
myArray2.view()

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Arange funtion helps to create arrays with regular increment values from start to end

In [39]:
test1 = numpy.arange(14)
print(testArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


### Linscace function will create array with a specified number of element acc to the specified number of element according to the specified size

In [50]:
test2 = numpy.linspace(12,14,5)
print(test2)

[12.  12.5 13.  13.5 14. ]


### zeros(shapes) funtion will create an array of the specified shape filled with value '0'. The default size is float64

In [53]:
test3 = numpy.zeros(4)
print(test3)
test4 = numpy.zeros((4))
print(test4)

[0. 0. 0. 0.]
[0. 0. 0. 0.]


### ones(shapes) funtion will create an array of specified shape filled with value '1'

In [56]:
test5 = numpy.ones(5)
print(test5)

[1. 1. 1. 1. 1.]


## Funtions for 1D Array

In [58]:
Arr = numpy.array([13,24,22,13,11,28,16,24,18])
print(Arr)

[13 24 22 13 11 28 16 24 18]


### 1.  Modify

In [60]:
Arr[3]=45
print(Arr)

[13 24 22 45 11 28 16 24 18]


### 2. Size

In [62]:
print(Arr.size)

9


### 3. dtype 

In [63]:
print(Arr.dtype)

int32


### 4. Mean

In [66]:
print(numpy.mean(Arr))

22.333333333333332


### 5. Median

In [67]:
print(numpy.median(Arr))

22.0


### 6. Min

In [68]:
print(numpy.min(Arr))

11


### 7.  Max

In [69]:
print(numpy.max(Arr))

45


### 8. Sum

In [71]:
print(numpy.sum(Arr))

201


###  9. prod returns Product of all the element

In [72]:
print(numpy.prod(Arr))

443400192


### 10. cov returns the covariance of all array element

In [73]:
print(numpy.cov(Arr))

103.25


### 11. var function returns the variance of all array element

In [74]:
print(numpy.var(Arr))

91.77777777777777


### 12. std returns Standard Deviation of all array element

In [75]:
print(numpy.std(Arr))

9.580071908799942


### 13. sort returns the elements in a sorted array

In [76]:
print(numpy.sort(Arr))

[11 13 16 18 22 24 24 28 45]


### 14. power returns all elements raised to the power of a number

In [78]:
print(numpy.power(Arr,3))

[ 2197 13824 10648 91125  1331 21952  4096 13824  5832]


### 15. sqrt returns the square root of all the element 

In [79]:
print(numpy.sqrt(Arr))

[3.60555128 4.89897949 4.69041576 6.70820393 3.31662479 5.29150262
 4.         4.89897949 4.24264069]


### 16. abs returns the absolute values of all the element 

In [80]:
print(numpy.abs(Arr))

[13 24 22 45 11 28 16 24 18]


### 17. sin returns the sine values of all the element

In [81]:
print(numpy.sin(Arr))

[ 0.42016704 -0.90557836 -0.00885131  0.85090352 -0.99999021  0.27090579
 -0.28790332 -0.90557836 -0.75098725]


### 18. cos returns the cos values of all the element 

In [82]:
print(numpy.cos(Arr))

[ 0.90744678  0.42417901 -0.99996083  0.52532199  0.0044257  -0.96260587
 -0.95765948  0.42417901  0.66031671]


### 19. tan returns the tan values of all the element

In [83]:
print(numpy.tan(Arr))

[ 4.63021133e-01 -2.13489670e+00  8.85165604e-03  1.61977519e+00
 -2.25950846e+02 -2.81429605e-01  3.00632242e-01 -2.13489670e+00
 -1.13731371e+00]


### 20. log reuturns the log with exponantial base of all element

In [84]:
print(numpy.log(Arr))

[2.56494936 3.17805383 3.09104245 3.80666249 2.39789527 3.33220451
 2.77258872 3.17805383 2.89037176]


### 21. log10 returns the log with base 10 of all the elements

In [85]:
print(numpy.log10(Arr))

[1.11394335 1.38021124 1.34242268 1.65321251 1.04139269 1.44715803
 1.20411998 1.38021124 1.25527251]


### 22. exp returns the exponential of all the elements

In [86]:
print(numpy.exp(Arr))

[4.42413392e+05 2.64891221e+10 3.58491285e+09 3.49342711e+19
 5.98741417e+04 1.44625706e+12 8.88611052e+06 2.64891221e+10
 6.56599691e+07]


## Multidimensional Array

In [87]:
import numpy as np

### 1. creating 2D Array using array function

In [88]:
arr1 = np.array([[100,200,300,400],[600,700,800,900]])
print(arr1)

[[100 200 300 400]
 [600 700 800 900]]


### 2. Creating 2D Array using matrix function

In [89]:
arr2 = np.matrix('11,22;33,44;55,66')
print(arr2)

[[11 22]
 [33 44]
 [55 66]]


### 3. Creating 2D Array using reshape function

In [95]:
arr3=np.array([10,20,30,40,50,60])
newarr = np.reshape(arr3,(3,2))
print(newarr)

[[10 20]
 [30 40]
 [50 60]]


### 4. Creating 2D array using zeros function

In [101]:
arr4 = np.zeros((4,2))
print(arr4)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### 5. Creating 2D array using ones funtion

In [102]:
arr5 = np.ones((4,2))
print(arr5)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### 6. Transpose funtion rerturns the transpose of a matrix

In [105]:
arr6=np.array([[10,60,40],[40,50,30],[50,60,40],[40,50,20]])
print(np.transpose(arr6))

[[10 40 50 40]
 [60 50 60 50]
 [40 30 40 20]]


### 7. ndim determines the dimension of the array

In [106]:
print(numpy.ndim(arr6))

2


### 8. shape determines shape of the array

In [107]:
print(numpy.shape(arr6))

(4, 3)


### 9. flatten used to flattens matrix and convert one dimension array

In [110]:
print(arr6.flatten())

[10 60 40 40 50 30 50 60 40 40 50 20]


### 10. sort() sort the matrix on column basis

In [111]:
print(numpy.sort(arr6))

[[10 40 60]
 [30 40 50]
 [40 50 60]
 [20 40 50]]


### 11. sort() sort the matrix on row basis

In [112]:
print(numpy.sort(arr6, axis = 0))

[[10 50 20]
 [40 50 30]
 [40 60 40]
 [50 60 40]]


### 12. diagonal function is help to determine the diagonal elements

In [114]:
print(numpy.diagonal(arr6))

[10 50 40]


# *** Thank You ***